
export async function initAtlas(districts,options){
 const stage=document.querySelector('#map-stage');const {signal}=options;const [THREE,geo]=await Promise.all([import(/* @vite-ignore */ '/assets/three.module.js'),fetch('/assets/gujarat-land.json',{signal}).then(r=>r.json())]);if(signal?.aborted)return ()=>{};let stopped=false,raf;
 const renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setClearColor(0,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.setSize(stage.clientWidth,stage.clientHeight);
 renderer.domElement.className='atlas-canvas';renderer.domElement.setAttribute('aria-hidden','true');
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,stage.clientWidth/stage.clientHeight,.1,100);camera.position.set(0,6.2,8.9);camera.lookAt(0,0,0);const root=new THREE.Group();scene.add(root);
 scene.add(new THREE.HemisphereLight(0xfff7df,0x274f50,2.8));const sun=new THREE.DirectionalLight(0xffe0ac,3.2);sun.position.set(-4,7,5);scene.add(sun);const rim=new THREE.DirectionalLight(0xa4d9cc,1.5);rim.position.set(5,2,-5);scene.add(rim);
 const project=(lon,lat)=>[(lon-71.25)*.93,lat-22.65];
 const earth=new THREE.Group();root.add(earth);earth.rotation.x=-Math.PI/2;
 geo.forEach(f=>{f.rings.forEach(r=>{if(r.length<4)return;const s=new THREE.Shape();r.forEach(([x,y],i)=>{const p=project(x,y);if(i)s.lineTo(...p);else s.moveTo(...p)});const g=new THREE.ExtrudeGeometry(s,{depth:.12,bevelEnabled:false,steps:1,curveSegments:1});const lat=r.reduce((a,p)=>a+p[1],0)/r.length;const m=new THREE.MeshStandardMaterial({color:lat>23.3?0xd8c9a7:lat<21.6?0x8ba58a:0xb9bb98,roughness:.8,metalness:.08});earth.add(new THREE.Mesh(g,m));});});
 const base=new THREE.Mesh(new THREE.PlaneGeometry(15,12),new THREE.MeshBasicMaterial({color:0xadcfc1,transparent:true,opacity:.018,side:THREE.DoubleSide}));base.rotation.x=-Math.PI/2;base.position.y=-.03;scene.add(base);
 const particlePositions=new Float32Array(120*3);for(let i=0;i<120;i++){const a=i*2.3999,r=2+Math.sqrt(i/120)*2.4;particlePositions[i*3]=Math.cos(a)*r;particlePositions[i*3+1]=.3+(i%11)*.035;particlePositions[i*3+2]=Math.sin(a)*r;}const pg=new THREE.BufferGeometry();pg.setAttribute('position',new THREE.BufferAttribute(particlePositions,3));const dust=new THREE.Points(pg,new THREE.PointsMaterial({color:0xe8d5a0,size:.018,transparent:true,opacity:.30}));scene.add(dust);
 const ringGeo=new THREE.TorusGeometry(.046,.011,6,18),sphereGeo=new THREE.SphereGeometry(.025,10,8);const pins=[];
 const overlay=document.createElement('div');overlay.className='district-pin-layer';const tooltip=document.createElement('div');tooltip.className='district-hover';tooltip.hidden=true;tooltip.setAttribute('role','group');tooltip.setAttribute('aria-label','District story preview');stage.append(tooltip);
 const tooltipTitles={kutch:'Salt, archaeology & craft',north:'Water, stone & woven heritage',central:'Cities, communities & living history',saurashtra:'Coast, pilgrimage & wild landscapes',south:'A journey through southern Gujarat'};
 let pinned=-1,interacted=false;let dismissTimer;const hideTip=()=>{if(pinned>=0)return;dismissTimer=setTimeout(()=>{if(pinned<0){tooltip.hidden=true;active=-1}},240)};tooltip.onpointerenter=()=>clearTimeout(dismissTimer);tooltip.onpointerleave=hideTip;tooltip.onfocusin=()=>clearTimeout(dismissTimer);tooltip.onfocusout=event=>{if(!tooltip.contains(event.relatedTarget))hideTip()};
 let active=-1,rotation=0,targetRotation=0,pitch=0,targetPitch=0,roll=0,targetRoll=0,zoom=1,targetZoom=1,drag=false,startX=0,startY=0,moved=false,focused=-1;
 function select(id,showTip=true){clearTimeout(dismissTimer);active=id;const d=districts[id];if(!d)return;const preview=options.episodes[d.episodes[0]];tooltip.innerHTML=`${pinned>=0?'<button class="unpin-district" aria-label="Close selected district preview">×</button>':''}<img src="assets/${preview.image}" alt="Related story: ${preview.title}"><span class="eyebrow">DISTRICT ${String(id+1).padStart(2,'0')} / 34</span><strong lang="gu">${d.gu}</strong><span>${d.name}</span><p>${tooltipTitles[d.region]}</p><small>Related journeys in Gujarat</small>${d.episodes.slice(0,2).map(key=>`<button data-episode="${key}">▷ ${options.episodes[key].gu}</button>`).join('')}<button data-district="${id}">District details ↗</button>`;const unpin=tooltip.querySelector('.unpin-district');if(unpin)unpin.onclick=()=>{pinned=-1;active=-1;tooltip.hidden=true;};tooltip.hidden=!showTip;overlay.querySelectorAll('button').forEach((b,i)=>{b.classList.toggle('selected',i===id);b.style.zIndex=i===id?'8':'1';});}
 districts.forEach((d,i)=>{const p=project(d.lon,d.lat),group=new THREE.Group();group.position.set(p[0],.16,-p[1]);const ring=new THREE.Mesh(ringGeo,new THREE.MeshBasicMaterial({color:0xf4db9a}));ring.rotation.x=Math.PI/2;const orb=new THREE.Mesh(sphereGeo,new THREE.MeshBasicMaterial({color:0xfff4ce}));orb.position.y=.027;group.add(ring,orb);root.add(group);pins.push(group);const b=document.createElement('button');b.className='district-pin';b.setAttribute('aria-label',`${d.name} · ${d.gu} · Open district stories`);b.innerHTML=`<span></span><small>${d.name}</small>`;b.onpointerenter=()=>{if(pinned<0)select(i)};b.onpointerleave=()=>{if(focused!==i)hideTip()};b.onfocus=()=>{focused=i;if(pinned<0)select(i)};b.onblur=()=>{focused=-1;hideTip()};b.onclick=ev=>{ev.stopPropagation();if(moved)return;pinned=i;interacted=true;select(i,true)};overlay.append(b)});
 renderer.render(scene,camera);document.querySelector('#map-plane').hidden=true;stage.prepend(renderer.domElement);stage.append(overlay);stage.append(tooltip);stage.addEventListener('keydown',event=>{if(event.key==='Escape'){clearTimeout(dismissTimer);tooltip.hidden=true;active=-1;pinned=-1;}},{signal});stage.classList.add('is-3d');
 document.querySelector('.atlas-top>span:last-child').textContent='34 DISTRICTS · 3D EXPLORER';document.querySelector('.atlas-bottom>span:first-child').innerHTML='<span class="tiny-dot"></span> Drag to orbit · Click a district to keep it open';document.querySelector('.map-caption').textContent='REFERENCE POINTS · NOT BOUNDARIES';
 const north=()=>{interacted=true;targetRotation=0;targetPitch=0;targetRoll=0;};
 stage.tabIndex=0;stage.setAttribute('aria-label','Gujarat 3D atlas. Drag to orbit, Shift-drag to roll. Arrow keys orbit, Q and E roll, N aligns north.');
 stage.onpointerdown=e=>{if(e.target.closest('button,.district-hover'))return;drag=true;interacted=true;startX=e.clientX;startY=e.clientY;moved=false;stage.setPointerCapture?.(e.pointerId)};
 stage.onpointermove=e=>{if(!drag)return;const dx=e.clientX-startX,dy=e.clientY-startY;if(Math.abs(dx)+Math.abs(dy)>3)moved=true;if(e.shiftKey)targetRoll+=dx*.006;else{targetRotation+=dx*.006;targetPitch+=dy*.006;}startX=e.clientX;startY=e.clientY;};
 const end=e=>{drag=false;if(stage.hasPointerCapture?.(e.pointerId))stage.releasePointerCapture(e.pointerId);setTimeout(()=>moved=false,0)};stage.onpointerup=end;stage.onpointercancel=end;
 const tools=document.querySelector('.map-tools');const rollButtons=[];
 for(const [label,value,glyph] of [['Roll left',-.25,'↶'],['Roll right',.25,'↷']]){const b=document.createElement('button');b.type='button';b.setAttribute('aria-label',label);b.title=label;b.textContent=glyph;b.onclick=()=>{interacted=true;targetRoll+=value};tools.append(b);rollButtons.push(b)}
 document.querySelector('#north-map').onclick=north;
 document.querySelector('#zoom-in').onclick=()=>targetZoom=Math.min(1.65,targetZoom+.15);document.querySelector('#zoom-out').onclick=()=>targetZoom=Math.max(.7,targetZoom-.15);document.querySelector('#reset-map').onclick=()=>{north();targetZoom=1;active=-1;pinned=-1;tooltip.hidden=true};
 stage.addEventListener('keydown',e=>{if(e.target!==stage)return;const keys=['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','q','e','n'];if(!keys.includes(e.key))return;e.preventDefault();interacted=true;if(e.key==='ArrowLeft')targetRotation-=.15;if(e.key==='ArrowRight')targetRotation+=.15;if(e.key==='ArrowUp')targetPitch-=.15;if(e.key==='ArrowDown')targetPitch+=.15;if(e.key==='q')targetRoll-=.15;if(e.key==='e')targetRoll+=.15;if(e.key==='n')north();},{signal});
 window.addEventListener('districtselect',e=>{pinned=e.detail;select(e.detail,true)},{signal});
 const v=new THREE.Vector3();const buttons=[...overlay.children];let visible=true;const visibilityObserver=new IntersectionObserver(es=>{visible=es[0].isIntersecting});visibilityObserver.observe(stage);
 const resize=new ResizeObserver(()=>{renderer.setSize(stage.clientWidth,stage.clientHeight);camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix()});resize.observe(stage);
 let last=0;function frame(t){if(stopped)return;raf=requestAnimationFrame(frame);if(!visible||document.hidden||t-last<32)return;last=t;const still=options.reduced();rotation=still?targetRotation:THREE.MathUtils.lerp(rotation,targetRotation,.08);zoom=still?targetZoom:THREE.MathUtils.lerp(zoom,targetZoom,.08);dust.rotation.y=still?0:t*.000008;pitch=still?targetPitch:THREE.MathUtils.lerp(pitch,targetPitch,.08);roll=still?targetRoll:THREE.MathUtils.lerp(roll,targetRoll,.08);root.rotation.set(pitch,rotation+(still||drag||interacted?0:Math.sin(t*.00013)*.035),roll);root.scale.setScalar(zoom);root.updateMatrixWorld(true);
 pins.forEach((pin,i)=>{const y=i===active?.30:.16;pin.position.y=still?y:THREE.MathUtils.lerp(pin.position.y,y,.14);pin.scale.setScalar(i===active?1.6:1);pin.getWorldPosition(v);v.project(camera);const x=(v.x*.5+.5)*stage.clientWidth,y2=(-v.y*.5+.5)*stage.clientHeight;buttons[i].style.left=x+'px';buttons[i].style.top=y2+'px';buttons[i].style.visibility=v.z>1||v.z< -1||x<3||x>stage.clientWidth-3||y2<0||y2>stage.clientHeight?'hidden':'visible';});renderer.render(scene,camera)}raf=requestAnimationFrame(frame);
 renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();renderer.domElement.hidden=true;overlay.hidden=true;tooltip.hidden=true;document.querySelector('#map-plane').hidden=false;document.querySelector('.atlas-bottom>span:first-child').textContent='2D atlas · browse the district directory below'},{signal});
 return ()=>{stopped=true;cancelAnimationFrame(raf);clearTimeout(dismissTimer);resize.disconnect();visibilityObserver.disconnect();rollButtons.forEach(b=>b.remove());document.querySelector('#north-map').onclick=null;stage.onpointerdown=stage.onpointermove=stage.onpointerup=stage.onpointercancel=null;const geometries=new Set(),materials=new Set();scene.traverse(node=>{if(node.geometry)geometries.add(node.geometry);if(node.material)(Array.isArray(node.material)?node.material:[node.material]).forEach(m=>materials.add(m))});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());renderer.dispose();renderer.domElement.remove();overlay.remove();tooltip.remove();document.querySelector('#map-plane').hidden=false;stage.classList.remove('is-3d');};
}
