// Native media stays on the original user gesture: no delayed React effect starts speech.
export function createStoryPlayer({ $, $$, episodes, esc, sourceLink, open, isReduced, onCleanup, renderKnowledge=()=>'' }) {
function showEpisode(id,autoplay=true){
 const e=episodes[id];if(!e)return;
 let chapter=0,english=false,disposed=false,request=0;
 const media=new Audio();media.preload='metadata';let volume=1;
 try{const saved=localStorage.getItem('gujarat-volume');if(saved!==null)volume=Math.max(0,Math.min(1,Number(saved)||0));}catch{}
 media.volume=volume;
 const fmt=n=>{n=Math.floor(Number.isFinite(n)?n:0);return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`};
 open(`<div class="cinema" id="cinema"><div class="cinema-stage"><img id="cinema-image" src="assets/${e.image}" alt="${esc(e.title)}"><div class="cinema-scrim"></div><span class="cinema-kicker">GUJARAT UNVEILED / ${e.kind.toUpperCase()}</span><div class="cinema-caption"><span id="scene-number"></span><h2 id="detail-title" lang="gu"></h2><p id="scene-caption" lang="gu"></p></div><div class="cinema-progress">${e.chapters.map((_,i)=>`<button data-scene="${i}" aria-label="Go to chapter ${i+1}"><span></span></button>`).join('')}</div></div><div class="cinema-controls"><button id="prev-scene" aria-label="Previous chapter">⏮</button><button id="play-story" class="play-story" aria-label="Play Gujarati narration">▶</button><button id="next-scene" aria-label="Next chapter">⏭</button><span id="play-time">00:00</span><div class="cinema-options"><button id="mute-story" aria-label="Mute narration">🔊</button><label class="volume-control">Volume <input id="story-volume" type="range" min="0" max="1" step="0.05" value="${volume}" aria-label="Narration volume"></label><button id="subtitles" aria-pressed="false">English captions</button><button id="fullscreen" aria-label="Toggle fullscreen">⛶</button></div></div><label class="story-seek">Chapter progress<input id="story-seek" type="range" min="0" max="100" step="0.1" value="0" aria-label="Seek within chapter"></label></div><div class="detail-body story-detail"><span class="eyebrow">${e.kind.toUpperCase()} · ${e.chapters.length} CHAPTERS</span><h3 lang="gu">${e.gu}</h3><p id="voice-status" class="voice-status" role="status">▶ દબાવો અને ગુજરાતીમાં વાર્તા સાંભળો.</p><div class="voice-select-row"><label for="voice-speed">Narration pace</label><select id="voice-speed"><option value="0.85">Gentle</option><option value="1" selected>Natural</option><option value="1.1">Brisk</option></select></div><div class="chapter-list">${e.chapters.map((c,i)=>`<button data-jump="${i}"><span>${String(i+1).padStart(2,'0')}</span><span lang="gu">${c[0]}</span><b>▷</b></button>`).join('')}</div><div class="source-links">${sourceLink(e.source)}</div><p class="story-type-note">Animated photo story with Gujarati AI narration. Audio is included; no installed device voice is needed. Pronunciation has not yet been reviewed by a native narrator. <a href="https://huggingface.co/facebook/mms-tts-guj" target="_blank" rel="noopener noreferrer">Meta MMS Gujarati · CC BY-NC 4.0 ↗</a></p>${renderKnowledge(id,true)}<button class="text-button" id="continue-story">Continue to the next story ↗</button></div>`,'cinema-dialog');
 const status=s=>{if(!disposed)$('#voice-status').textContent=s};
 function controls(){if(disposed)return;const active=!media.paused&&!media.ended;$('#play-story').textContent=active?'Ⅱ':'▶';$('#play-story').setAttribute('aria-label',active?'Pause narration':'Play Gujarati narration');$('#mute-story').textContent=media.muted||media.volume===0?'🔇':'🔊';$('#mute-story').setAttribute('aria-label',media.muted?'Unmute narration':'Mute narration');$('#mute-story').setAttribute('aria-pressed',media.muted);}
 function progress(){if(disposed)return;const duration=Number.isFinite(media.duration)?media.duration:0;$('#play-time').textContent=`${fmt(media.currentTime)} / ${fmt(duration)}`;$('#cinema-image').style.transform=`scale(${isReduced()||!duration?1:1+.13*media.currentTime/duration})`;$('#story-seek').disabled=!duration;$('#story-seek').value=duration?media.currentTime/duration*100:0;$$('[data-scene]').forEach((b,i)=>$('span',b).style.width=(i<chapter?100:i===chapter&&duration?media.currentTime/duration*100:0)+'%');}
 function paint(){const c=e.chapters[chapter];$('#detail-title').textContent=c[0];$('#scene-caption').textContent=english?c[2]:c[1];$('#scene-caption').lang=english?'en':'gu';$('#scene-number').textContent=`${String(chapter+1).padStart(2,'0')} / ${String(e.chapters.length).padStart(2,'0')}`;$('#cinema-image').style.objectPosition=['45% 50%','65% 40%','35% 60%','55% 35%','40% 65%'][chapter%5];$('#prev-scene').disabled=chapter===0;$('#next-scene').disabled=chapter===e.chapters.length-1;$$('[data-jump]').forEach((b,i)=>{b.classList.toggle('active',i===chapter);b.setAttribute('aria-current',i===chapter?'step':'false')});progress();controls();}
 async function start(){const ticket=++request;status('વાર્તાનો અવાજ શરૂ થઈ રહ્યો છે…');try{await media.play();if(disposed||ticket!==request)return;status('ગુજરાતી વાર્તા · અવાજ સાથે સફર');controls();}catch(error){if(disposed||ticket!==request||error.name==='AbortError')return;status('અવાજ શરૂ થઈ શક્યો નથી. ફરી ▶ દબાવો. Check your connection and laptop output volume.');controls();}}
 function load(i,autoplay=false){request++;media.pause();chapter=Math.max(0,Math.min(e.chapters.length-1,i));media.src=`assets/audio/${id}-${chapter+1}.mp3`;media.load();paint();if(autoplay)start();}
 function pause(){request++;media.pause();controls();status('વાર્તા થોભાવી છે. આગળ સાંભળવા ▶ દબાવો.');}
 $('#play-story').onclick=()=>{if(!media.paused){pause();return}if(media.ended&&chapter===e.chapters.length-1)load(0);if(media.error)media.load();start();};
 $('#prev-scene').onclick=()=>load(chapter-1,!media.paused);$('#next-scene').onclick=()=>load(chapter+1,!media.paused);
 $$('[data-scene]').forEach(b=>b.onclick=()=>load(+b.dataset.scene,!media.paused));$$('[data-jump]').forEach(b=>b.onclick=()=>load(+b.dataset.jump,true));
 $('#story-volume').oninput=ev=>{media.volume=+ev.target.value;media.muted=false;try{localStorage.setItem('gujarat-volume',media.volume)}catch{}controls()};$('#mute-story').onclick=()=>{media.muted=!media.muted;if(!media.muted&&media.volume===0){media.volume=1;$('#story-volume').value=1;}controls()};
 $('#story-seek').oninput=ev=>{if(Number.isFinite(media.duration))media.currentTime=+ev.target.value/100*media.duration};$('#voice-speed').onchange=ev=>media.playbackRate=+ev.target.value;
 $('#subtitles').onclick=()=>{english=!english;$('#subtitles').setAttribute('aria-pressed',english);paint()};
 $('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('#cinema').requestFullscreen()}catch{status('Fullscreen is not available in this browser.')}};
 $('#continue-story').onclick=()=>{const keys=Object.keys(episodes);showEpisode(keys[(keys.indexOf(id)+1)%keys.length])};
 media.ontimeupdate=progress;media.onloadedmetadata=progress;media.onplay=controls;media.onpause=controls;media.onplaying=()=>{controls();status('ગુજરાતી વાર્તા · અવાજ સાથે સફર')};media.onwaiting=()=>status('અવાજ લોડ થઈ રહ્યો છે…');media.onstalled=()=>status('Audio is buffering. Check your connection; playback will resume when ready.');media.onerror=()=>{controls();status('Audio could not load. Check your connection, then press Play to retry.')};
 media.onended=()=>{if(chapter<e.chapters.length-1)load(chapter+1,true);else{controls();status('વાર્તા પૂરી થઈ. ફરી સાંભળો અથવા આગળની વાર્તા પસંદ કરો.')}};
 const visibility=()=>{if(document.hidden&&!media.paused)pause()};document.addEventListener('visibilitychange',visibility);load(0,autoplay);
 onCleanup(()=>{disposed=true;request++;media.pause();media.removeAttribute('src');media.load();document.removeEventListener('visibilitychange',visibility);if(document.fullscreenElement)document.exitFullscreen().catch(()=>{})});
}

return showEpisode;
}
